# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Run unit tests

on: push

permissions: {}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 'lts/*'
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
